---
title: "Using daedalus.data and daedalus"
output: rmarkdown::html_vignette
bibliography: resources/references.json
link-citations: true
vignette: >
  %\VignetteIndexEntry{Using daedalus.data and daedalus}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

_daedalus.data_ is a package that provides input data to use in the DAEDALUS model.
This package never needs to be used directly when using the basic features of _daedalus_.

The idea behind having the data in a separate package is rather that country, infection, or scenario-specific data (or parameters) can be updated without needing to touch the larger _daedalus_ codebase.

The package provides data from @walker2020 on country demography, country workforce per economic sector, and social contacts between age groups in `country_data`.

The package also provides data from @jarvis2024 on workplace contacts in economic sectors.
Both datasets are accessed by internal functions to reduce the need for user input.

## Note on dependencies

This package is a dependency of _daedalus_ but also 'Suggests' _daedalus_ itself.
This is not a circular dependency; the idea is to allow users to access some epidemic-model parameters, such as the desired number of age groups, when preparing the raw data for use in the model.

## References
